version: "3"

services:
  jenkins:
    build: ./jenkins
    volumes:
      - jenkins_data:/home/myuser
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    environment:
      - ADMIN_TOKEN

volumes:
  jenkins_data:
